name = "ecom-task-api"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SESSIONS"
id = "9056ba53c5db4fbc9ee15b82849e8097"
preview_id = "339ba67c25fa4eb6b20eb56ba85bf03e"